### ISSUE TITLE
Can the runtime be updated even when there aren't new releases?

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.SoundJuicer#6]
Currently this is the only app pulling the GNOME 3.38 runtime on my device (which I believe is likely EOL as the GNOME 40 runtime is EOL?).

Is it possible or expected in the flathub ecosystem that apps should update their runtime to a supported / modern release even if the app doesn't change? Eg if SoundJuicer moved to the GNOME 41 or 42 runtime ?

**Comment by barthalion** [comment]
Just merged a PR fixing this.

**Comment by hadess** [comment]
> Just merged a PR fixing this.

I wish you wouldn't do that. Did you test that all the codecs compiled by the package itself still worked? We were building pre-mono-repo versions of GStreamer plugins and that needed to be updated.

**Comment by hadess** [comment]
FWIW, this update broke at least AAC ripping as the plugins were missing.

Should be fixed in https://github.com/flathub/org.gnome.SoundJuicer/pull/8
